name: Java CI with JUnit

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout code

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create directories
        run: |
          mkdir -p bin
          mkdir -p bin-tests

      - name: Compile main code
        run: |
          find src/main -name "*.java" > sources.txt
          javac -d bin @sources.txt

      - name: Compile tests
        run: |
          javac -d bin-tests -cp "bin:lib/junit.jar" src/test/CalculatorTest1.java src/test/CalculatorTest2.java

      - name: Run tests
        run: |
          java -cp "bin:bin-tests:lib/junit.jar" org.junit.runner.JUnitCore test.CalculatorTest1 test.CalculatorTest2
